// Code generated by "charstat"; DO NOT EDIT.

package lynx

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    67.2,
		ATKAdd:     3.36,
		DEFBase:    75,
		DEFAdd:     3.75,
		HPBase:     144,
		HPAdd:      7.2,
		SPD:        100,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    94.08,
		ATKAdd:     3.36,
		DEFBase:    105,
		DEFAdd:     3.75,
		HPBase:     201.6,
		HPAdd:      7.2,
		SPD:        100,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    120.96,
		ATKAdd:     3.36,
		DEFBase:    135,
		DEFAdd:     3.75,
		HPBase:     259.2,
		HPAdd:      7.2,
		SPD:        100,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    147.84,
		ATKAdd:     3.36,
		DEFBase:    165,
		DEFAdd:     3.75,
		HPBase:     316.8,
		HPAdd:      7.2,
		SPD:        100,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    174.72,
		ATKAdd:     3.36,
		DEFBase:    195,
		DEFAdd:     3.75,
		HPBase:     374.4,
		HPAdd:      7.2,
		SPD:        100,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    201.6,
		ATKAdd:     3.36,
		DEFBase:    225,
		DEFAdd:     3.75,
		HPBase:     432,
		HPAdd:      7.2,
		SPD:        100,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    228.48,
		ATKAdd:     3.36,
		DEFBase:    255,
		DEFAdd:     3.75,
		HPBase:     489.6,
		HPAdd:      7.2,
		SPD:        100,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.HPPercent,
		Amount: 0.04,
		Level: 1,
	},
	"202": {
		Stat: prop.DEFPercent,
		Amount: 0.05,
		Ascension: 2,
	},
	"203": {
		Stat: prop.HPPercent,
		Amount: 0.04,
		Ascension: 3,
	},
	"204": {
		Stat: prop.EffectRES,
		Amount: 0.04,
		Ascension: 3,
	},
	"205": {
		Stat: prop.HPPercent,
		Amount: 0.06,
		Ascension: 4,
	},
	"206": {
		Stat: prop.DEFPercent,
		Amount: 0.075,
		Ascension: 5,
	},
	"207": {
		Stat: prop.HPPercent,
		Amount: 0.06,
		Ascension: 5,
	},
	"208": {
		Stat: prop.EffectRES,
		Amount: 0.06,
		Ascension: 6,
	},
	"209": {
		Stat: prop.DEFPercent,
		Amount: 0.1,
		Level: 75,
	},
	"210": {
		Stat: prop.HPPercent,
		Amount: 0.08,
		Level: 80,
	},
}