// Code generated by "charstat"; DO NOT EDIT.

package trailblazerfire

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    81.84,
		ATKAdd:     4.092,
		DEFBase:    82.5,
		DEFAdd:     4.125,
		HPBase:     168.96,
		HPAdd:      8.448,
		SPD:        95,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      150,
	},
	{
		MaxLevel:   30,
		ATKBase:    114.576,
		ATKAdd:     4.092,
		DEFBase:    115.5,
		DEFAdd:     4.125,
		HPBase:     236.544,
		HPAdd:      8.448,
		SPD:        95,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      150,
	},
	{
		MaxLevel:   40,
		ATKBase:    147.312,
		ATKAdd:     4.092,
		DEFBase:    148.5,
		DEFAdd:     4.125,
		HPBase:     304.128,
		HPAdd:      8.448,
		SPD:        95,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      150,
	},
	{
		MaxLevel:   50,
		ATKBase:    180.048,
		ATKAdd:     4.092,
		DEFBase:    181.5,
		DEFAdd:     4.125,
		HPBase:     371.712,
		HPAdd:      8.448,
		SPD:        95,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      150,
	},
	{
		MaxLevel:   60,
		ATKBase:    212.784,
		ATKAdd:     4.092,
		DEFBase:    214.5,
		DEFAdd:     4.125,
		HPBase:     439.296,
		HPAdd:      8.448,
		SPD:        95,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      150,
	},
	{
		MaxLevel:   70,
		ATKBase:    245.52,
		ATKAdd:     4.092,
		DEFBase:    247.5,
		DEFAdd:     4.125,
		HPBase:     506.88,
		HPAdd:      8.448,
		SPD:        95,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      150,
	},
	{
		MaxLevel:   80,
		ATKBase:    278.256,
		ATKAdd:     4.092,
		DEFBase:    280.5,
		DEFAdd:     4.125,
		HPBase:     574.464,
		HPAdd:      8.448,
		SPD:        95,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      150,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.DEFPercent,
		Amount: 0.05,
		Level: 1,
	},
	"202": {
		Stat: prop.ATKPercent,
		Amount: 0.04,
		Ascension: 2,
	},
	"203": {
		Stat: prop.DEFPercent,
		Amount: 0.05,
		Ascension: 3,
	},
	"204": {
		Stat: prop.HPPercent,
		Amount: 0.04,
		Ascension: 3,
	},
	"205": {
		Stat: prop.DEFPercent,
		Amount: 0.075,
		Ascension: 4,
	},
	"206": {
		Stat: prop.ATKPercent,
		Amount: 0.06,
		Ascension: 5,
	},
	"207": {
		Stat: prop.DEFPercent,
		Amount: 0.075,
		Ascension: 5,
	},
	"208": {
		Stat: prop.HPPercent,
		Amount: 0.06,
		Ascension: 6,
	},
	"209": {
		Stat: prop.ATKPercent,
		Amount: 0.08,
		Level: 75,
	},
	"210": {
		Stat: prop.DEFPercent,
		Amount: 0.1,
		Level: 80,
	},
}