// Code generated by "charstat"; DO NOT EDIT.

package sparkle

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    71.28,
		ATKAdd:     3.564,
		DEFBase:    66,
		DEFAdd:     3.3,
		HPBase:     190.08,
		HPAdd:      9.504,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    99.792,
		ATKAdd:     3.564,
		DEFBase:    92.4,
		DEFAdd:     3.3,
		HPBase:     266.112,
		HPAdd:      9.504,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    128.304,
		ATKAdd:     3.564,
		DEFBase:    118.8,
		DEFAdd:     3.3,
		HPBase:     342.144,
		HPAdd:      9.504,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    156.816,
		ATKAdd:     3.564,
		DEFBase:    145.2,
		DEFAdd:     3.3,
		HPBase:     418.176,
		HPAdd:      9.504,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    185.328,
		ATKAdd:     3.564,
		DEFBase:    171.6,
		DEFAdd:     3.3,
		HPBase:     494.208,
		HPAdd:      9.504,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    213.84,
		ATKAdd:     3.564,
		DEFBase:    198,
		DEFAdd:     3.3,
		HPBase:     570.24,
		HPAdd:      9.504,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    242.352,
		ATKAdd:     3.564,
		DEFBase:    224.4,
		DEFAdd:     3.3,
		HPBase:     646.272,
		HPAdd:      9.504,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.HPPercent,
		Amount: 0.04,
		Level: 1,
	},
	"202": {
		Stat: prop.CritDMG,
		Amount: 0.053,
		Ascension: 2,
	},
	"203": {
		Stat: prop.HPPercent,
		Amount: 0.04,
		Ascension: 3,
	},
	"204": {
		Stat: prop.EffectRES,
		Amount: 0.04,
		Ascension: 3,
	},
	"205": {
		Stat: prop.HPPercent,
		Amount: 0.06,
		Ascension: 4,
	},
	"206": {
		Stat: prop.CritDMG,
		Amount: 0.08,
		Ascension: 5,
	},
	"207": {
		Stat: prop.HPPercent,
		Amount: 0.06,
		Ascension: 5,
	},
	"208": {
		Stat: prop.EffectRES,
		Amount: 0.06,
		Ascension: 6,
	},
	"209": {
		Stat: prop.CritDMG,
		Amount: 0.107,
		Level: 75,
	},
	"210": {
		Stat: prop.HPPercent,
		Amount: 0.08,
		Level: 80,
	},
}