// Code generated by "charstat"; DO NOT EDIT.

package drratio

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    105.6,
		ATKAdd:     5.28,
		DEFBase:    62.7,
		DEFAdd:     3.135,
		HPBase:     142.56,
		HPAdd:      7.128,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      75,
	},
	{
		MaxLevel:   30,
		ATKBase:    147.84,
		ATKAdd:     5.28,
		DEFBase:    87.78,
		DEFAdd:     3.135,
		HPBase:     199.584,
		HPAdd:      7.128,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      75,
	},
	{
		MaxLevel:   40,
		ATKBase:    190.08,
		ATKAdd:     5.28,
		DEFBase:    112.86,
		DEFAdd:     3.135,
		HPBase:     256.608,
		HPAdd:      7.128,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      75,
	},
	{
		MaxLevel:   50,
		ATKBase:    232.32,
		ATKAdd:     5.28,
		DEFBase:    137.94,
		DEFAdd:     3.135,
		HPBase:     313.632,
		HPAdd:      7.128,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      75,
	},
	{
		MaxLevel:   60,
		ATKBase:    274.56,
		ATKAdd:     5.28,
		DEFBase:    163.02,
		DEFAdd:     3.135,
		HPBase:     370.656,
		HPAdd:      7.128,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      75,
	},
	{
		MaxLevel:   70,
		ATKBase:    316.8,
		ATKAdd:     5.28,
		DEFBase:    188.1,
		DEFAdd:     3.135,
		HPBase:     427.68,
		HPAdd:      7.128,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      75,
	},
	{
		MaxLevel:   80,
		ATKBase:    359.04,
		ATKAdd:     5.28,
		DEFBase:    213.18,
		DEFAdd:     3.135,
		HPBase:     484.704,
		HPAdd:      7.128,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      75,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.ATKPercent,
		Amount: 0.04,
		Level: 1,
	},
	"202": {
		Stat: prop.CritChance,
		Amount: 0.026999999,
		Ascension: 2,
	},
	"203": {
		Stat: prop.ATKPercent,
		Amount: 0.04,
		Ascension: 3,
	},
	"204": {
		Stat: prop.DEFPercent,
		Amount: 0.05,
		Ascension: 3,
	},
	"205": {
		Stat: prop.ATKPercent,
		Amount: 0.06,
		Ascension: 4,
	},
	"206": {
		Stat: prop.CritChance,
		Amount: 0.04,
		Ascension: 5,
	},
	"207": {
		Stat: prop.ATKPercent,
		Amount: 0.06,
		Ascension: 5,
	},
	"208": {
		Stat: prop.DEFPercent,
		Amount: 0.075,
		Ascension: 6,
	},
	"209": {
		Stat: prop.CritChance,
		Amount: 0.053,
		Level: 75,
	},
	"210": {
		Stat: prop.ATKPercent,
		Amount: 0.08,
		Level: 80,
	},
}