// Code generated by "charstat"; DO NOT EDIT.

package jade

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    89.76,
		ATKAdd:     4.488,
		DEFBase:    69.3,
		DEFAdd:     3.465,
		HPBase:     147.84,
		HPAdd:      7.392,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      75,
	},
	{
		MaxLevel:   30,
		ATKBase:    125.664,
		ATKAdd:     4.488,
		DEFBase:    97.02,
		DEFAdd:     3.465,
		HPBase:     206.976,
		HPAdd:      7.392,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      75,
	},
	{
		MaxLevel:   40,
		ATKBase:    161.568,
		ATKAdd:     4.488,
		DEFBase:    124.74,
		DEFAdd:     3.465,
		HPBase:     266.112,
		HPAdd:      7.392,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      75,
	},
	{
		MaxLevel:   50,
		ATKBase:    197.472,
		ATKAdd:     4.488,
		DEFBase:    152.46,
		DEFAdd:     3.465,
		HPBase:     325.248,
		HPAdd:      7.392,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      75,
	},
	{
		MaxLevel:   60,
		ATKBase:    233.376,
		ATKAdd:     4.488,
		DEFBase:    180.18,
		DEFAdd:     3.465,
		HPBase:     384.384,
		HPAdd:      7.392,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      75,
	},
	{
		MaxLevel:   70,
		ATKBase:    269.28,
		ATKAdd:     4.488,
		DEFBase:    207.9,
		DEFAdd:     3.465,
		HPBase:     443.52,
		HPAdd:      7.392,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      75,
	},
	{
		MaxLevel:   80,
		ATKBase:    305.184,
		ATKAdd:     4.488,
		DEFBase:    235.62,
		DEFAdd:     3.465,
		HPBase:     502.656,
		HPAdd:      7.392,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      75,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.QuantumDamagePercent,
		Amount: 0.032,
		Level: 1,
	},
	"202": {
		Stat: prop.ATKPercent,
		Amount: 0.04,
		Ascension: 2,
	},
	"203": {
		Stat: prop.QuantumDamagePercent,
		Amount: 0.032,
		Ascension: 3,
	},
	"204": {
		Stat: prop.EffectRES,
		Amount: 0.04,
		Ascension: 3,
	},
	"205": {
		Stat: prop.QuantumDamagePercent,
		Amount: 0.048,
		Ascension: 4,
	},
	"206": {
		Stat: prop.ATKPercent,
		Amount: 0.06,
		Ascension: 5,
	},
	"207": {
		Stat: prop.QuantumDamagePercent,
		Amount: 0.048,
		Ascension: 5,
	},
	"208": {
		Stat: prop.EffectRES,
		Amount: 0.06,
		Ascension: 6,
	},
	"209": {
		Stat: prop.ATKPercent,
		Amount: 0.08,
		Level: 75,
	},
	"210": {
		Stat: prop.QuantumDamagePercent,
		Amount: 0.064,
		Level: 80,
	},
}