// Code generated by "charstat"; DO NOT EDIT.

package acheron

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    95.04,
		ATKAdd:     4.752,
		DEFBase:    59.4,
		DEFAdd:     2.97,
		HPBase:     153.12,
		HPAdd:      7.656,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    133.056,
		ATKAdd:     4.752,
		DEFBase:    83.16,
		DEFAdd:     2.97,
		HPBase:     214.368,
		HPAdd:      7.656,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    171.072,
		ATKAdd:     4.752,
		DEFBase:    106.92,
		DEFAdd:     2.97,
		HPBase:     275.616,
		HPAdd:      7.656,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    209.088,
		ATKAdd:     4.752,
		DEFBase:    130.68,
		DEFAdd:     2.97,
		HPBase:     336.864,
		HPAdd:      7.656,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    247.104,
		ATKAdd:     4.752,
		DEFBase:    154.44,
		DEFAdd:     2.97,
		HPBase:     398.112,
		HPAdd:      7.656,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    285.12,
		ATKAdd:     4.752,
		DEFBase:    178.2,
		DEFAdd:     2.97,
		HPBase:     459.36,
		HPAdd:      7.656,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    323.136,
		ATKAdd:     4.752,
		DEFBase:    201.96,
		DEFAdd:     2.97,
		HPBase:     520.608,
		HPAdd:      7.656,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.ATKPercent,
		Amount: 0.04,
		Level: 1,
	},
	"202": {
		Stat: prop.CritDMG,
		Amount: 0.053,
		Ascension: 2,
	},
	"203": {
		Stat: prop.ATKPercent,
		Amount: 0.04,
		Ascension: 3,
	},
	"204": {
		Stat: prop.ThunderDamagePercent,
		Amount: 0.032,
		Ascension: 3,
	},
	"205": {
		Stat: prop.ATKPercent,
		Amount: 0.06,
		Ascension: 4,
	},
	"206": {
		Stat: prop.CritDMG,
		Amount: 0.08,
		Ascension: 5,
	},
	"207": {
		Stat: prop.ATKPercent,
		Amount: 0.06,
		Ascension: 5,
	},
	"208": {
		Stat: prop.ThunderDamagePercent,
		Amount: 0.048,
		Ascension: 6,
	},
	"209": {
		Stat: prop.CritDMG,
		Amount: 0.107,
		Level: 75,
	},
	"210": {
		Stat: prop.ATKPercent,
		Amount: 0.08,
		Level: 80,
	},
}