// Code generated by "charstat"; DO NOT EDIT.

package aventurine

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    60.72,
		ATKAdd:     3.036,
		DEFBase:    89.1,
		DEFAdd:     4.455,
		HPBase:     163.68,
		HPAdd:      8.184,
		SPD:        106,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      150,
	},
	{
		MaxLevel:   30,
		ATKBase:    85.008,
		ATKAdd:     3.036,
		DEFBase:    124.74,
		DEFAdd:     4.455,
		HPBase:     229.152,
		HPAdd:      8.184,
		SPD:        106,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      150,
	},
	{
		MaxLevel:   40,
		ATKBase:    109.296,
		ATKAdd:     3.036,
		DEFBase:    160.38,
		DEFAdd:     4.455,
		HPBase:     294.624,
		HPAdd:      8.184,
		SPD:        106,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      150,
	},
	{
		MaxLevel:   50,
		ATKBase:    133.584,
		ATKAdd:     3.036,
		DEFBase:    196.02,
		DEFAdd:     4.455,
		HPBase:     360.096,
		HPAdd:      8.184,
		SPD:        106,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      150,
	},
	{
		MaxLevel:   60,
		ATKBase:    157.872,
		ATKAdd:     3.036,
		DEFBase:    231.66,
		DEFAdd:     4.455,
		HPBase:     425.568,
		HPAdd:      8.184,
		SPD:        106,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      150,
	},
	{
		MaxLevel:   70,
		ATKBase:    182.16,
		ATKAdd:     3.036,
		DEFBase:    267.3,
		DEFAdd:     4.455,
		HPBase:     491.04,
		HPAdd:      8.184,
		SPD:        106,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      150,
	},
	{
		MaxLevel:   80,
		ATKBase:    206.448,
		ATKAdd:     3.036,
		DEFBase:    302.94,
		DEFAdd:     4.455,
		HPBase:     556.512,
		HPAdd:      8.184,
		SPD:        106,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      150,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.DEFPercent,
		Amount: 0.05,
		Level: 1,
	},
	"202": {
		Stat: prop.ImaginaryDamagePercent,
		Amount: 0.032,
		Ascension: 2,
	},
	"203": {
		Stat: prop.DEFPercent,
		Amount: 0.05,
		Ascension: 3,
	},
	"204": {
		Stat: prop.EffectRES,
		Amount: 0.04,
		Ascension: 3,
	},
	"205": {
		Stat: prop.DEFPercent,
		Amount: 0.075,
		Ascension: 4,
	},
	"206": {
		Stat: prop.ImaginaryDamagePercent,
		Amount: 0.048,
		Ascension: 5,
	},
	"207": {
		Stat: prop.DEFPercent,
		Amount: 0.075,
		Ascension: 5,
	},
	"208": {
		Stat: prop.EffectRES,
		Amount: 0.06,
		Ascension: 6,
	},
	"209": {
		Stat: prop.ImaginaryDamagePercent,
		Amount: 0.064,
		Level: 75,
	},
	"210": {
		Stat: prop.DEFPercent,
		Amount: 0.1,
		Level: 80,
	},
}